{%set name = "requests-futures" %}
{%set version = "0.9.4" %}
{%set hash_type = "sha256" %}
{%set hash_val = "2046313d60a3e8bd868adf401694639a7fa963ef42648bb202f077f69d35207a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests >=1.2.0
    - futures >=2.1.3  # [py<32]

test:
  imports:
    - requests_futures

about:
  home: https://github.com/ross/requests-futures
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Asynchronous Python HTTP for Humans.'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
