{% set version = "0.9.8" %}

package:
  name: requests-futures
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/requests-futures/requests-futures-{{ version }}.tar.gz
  sha256: 76a22b95723267b53d8cc50e54d00b98d95afa02fd8449501b07a3797f46a96d

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests >=1.2.0
    - futures >=2.1.3  # [py<32]

test:
  imports:
    - requests_futures

about:
  home: https://github.com/ross/requests-futures
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Asynchronous Python HTTP for Humans'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
