travis:
  secure:
    BINSTAR_TOKEN: gA6I4VnMEPWhKawByKs9do6wdM55nme2F5LjuudqXeP07d5flPUZPZF5ae6iKDk+aYq0e6V6By1g3XsvSXfMrLl/5ctX+DdJYrA8iUMcFjuY2Tcn2Mzy6pCNfcNtDefy6uxizlUgEN9M14MbDWqsZi9qHRrZJltBpOhU0UIomEgXv/lmRTUsgNyQGQI6+cdiUnb/KoCoN4vUfhrwsrOE/4tDK9lYOQWcJwSzxgzxJ6nv6Nj/9FoZHlvu3JD7Vn8ml8crPMYsDL2VE8V8BSOWoUMN/73PG6FuTemykTHU7DEWZqdA8rVTJ6HlE/yiqJ7iyYbEmVCSK/m2OTtZc5LwxJHsLPL38Aw41mI3Bnbh5XHcPoY6Cc5DnQxwQ8ncgUWst4Sti/CDGebB5CxOX17QiyfN93PellmibP68g8jGwL39UGIWloqD5XQbPacbAdRNmViqYUfFUYr2h0HtIDIjol0HNNaQ8xPoIKf3wpCszpuasuaPRB7+pbfxvjbBACYsEV3Qi8JBikcGnSNDWeSBmm4JUKjuPJRNOkktUI67wRvJIT1K/HgKSQ7D5zxk9nAypaKcEs4TMAUHJVWfW2tQxZRfU6NeTC9iDP5T/kTLtR49la+qqutC7D16+sh4wGCW9u5jwzObD9p/e0P34J27qmOrKTGQuVwfbKHr6390SZc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
