travis:
  secure:
    BINSTAR_TOKEN: OAwSym+qS02aqY02kI/I1e4XxiATNf+b0wOpoIfvKzKmUJMQTzqoGXTacwLyu+KdRoR8neyk/FMsTNVNvQKq/d1jgxwEyWETTOlukHULZdC47kw2PnOyaaUDOLe7Qt9eVjZFngwljPaz9JM4eHtKg76ezEzQE4/xYkV65vNVTO4AFhf0Qpf/3JvlXw5mSvXomLmrAgyGNO9atAhzz69uqhl+86Zqy3gwqH27Ro8XiRMTd5yVqSPsqdSn16K7ZERIqY8ex9TEM03E0OhVuY5ZcFdvDUUmTTcbj2cAKLE3rbxjmJ9Mw90jM2zMdmm1VDpLuHasjb93zK8xF0G261H925ManaYylz8f7xMMFR8vJocqLDia+Q7PUwiUDibQlDPjlBYkxy65JprX9eWghDXnRJp5kMG3KXDzxbpX7plHLfqEBY2Bv4l2fIMoc6E9GcCZqSr0qSspIFuTSJeiUEkTZXdmLb+vE9HmHVy7IjxkomteOjTkhzG3lH//Wr2UTORv+cHc6aTeSOohB++dilNAUqxt99yKy2EfU2vtuHTUd+IhtLArKmPfJXGxwIdqyjYaRAayZcpNwkWiLXurKg7kBSALHTQTGFowIWscpYil0JlOt33AHg1pnCFVDTYXOJPnfD1TLHFzYmidx9O333V4/nRd1ShC+gdJ8QKiWu8/6Lk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
