travis:
  secure:
    BINSTAR_TOKEN: PLlimAca2n/Vtdgkk8WEUzelw3fwRTfpcp1IS62KgghWUzPUn3J7IeBs7V+DCA2durRoLtKGpZWgj6tKbxBfxPK5MSyKaAMXVQHMq8QB1ERk67MtR2RfnxHfCS5tLBh3/qyM+8eRK+DzoNy3PPMEXNCa8P/ETUUBFNLQz5zBl/Rp9eu52vhT17TVn83jcjkWyCdO4ntMjfeP+vpH07zHT53h8VZtx5um5HdqFm99pCg0RAN/u5OVNC9Co0hZcH6+Cx+zty2YEoiA+9OlYyg5HiTyE3245+CgqjjRhHxmB23RBU6avPHGg/zrjWdEX8uLZ9fdXYNpnyopSllD4Xj10UyVPKQEtEOg19kKn2nN2IYHHpfRQa3Pr8vpwABaSXmraH+Q7FJqY/g8ufl7klBeW4ma3hhfOGBHjrqp7HpZ8J0/53FELG0rqrCkIhWGeUdYmVwFJNFPMUSzieJDtGr4IEeZU89Npc91UQXL2NE6M5Gwp35EWXzsglPqTtYDYNXRzc0xGvmsIGWlDWkZvZyBAmbd98VcGmd3xruQPuaX7fc2+mevNIiKEme2iiBW4MKj2VNRpai8CfQAge9ljTuHyEknMv1e8nYa9uocnU2JG85hIWAcA3dQ6j2tk+jBZLXiZFWhFvLVOIurytgsIYOhEcXyxvmpgcqkI/bZ/PfDw+g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
